# Problem 1


In [ ]:
# Define the joint probability distribution as a dictionary
# Format: (Toothache, Cavity, Catch): Probability
joint_prob = {
    ('Toothache', 'Cavity', 'Catch'): 0.108,
    ('Toothache', 'Cavity', '~Catch'): 0.012,
    ('Toothache', '~Cavity', 'Catch'): 0.016,
    ('Toothache', '~Cavity', '~Catch'): 0.064,
    ('~Toothache', 'Cavity', 'Catch'): 0.072,
    ('~Toothache', 'Cavity', '~Catch'): 0.008,
    ('~Toothache', '~Cavity', 'Catch'): 0.144,
    ('~Toothache', '~Cavity', '~Catch'): 0.576
}

# Function to calculate marginal probability
def marginal_probability(event, value):
    return sum(prob for (toothache, cavity, catch), prob in joint_prob.items() if locals()[event.lower()] == value)

# Function to calculate conditional probability P(A | B)
def conditional_probability(event_a, value_a, event_b, value_b):
    joint_events = [(toothache, cavity, catch) for (toothache, cavity, catch), prob in joint_prob.items()
                    if locals()[event_a.lower()] == value_a and locals()[event_b.lower()] == value_b]

    prob_joint = sum(joint_prob[event] for event in joint_events)
    prob_b = marginal_probability(event_b, value_b)

    return prob_joint / prob_b if prob_b else 0

# Q1 a) P(Toothache)
p_toothache = marginal_probability('Toothache', 'Toothache')
print("P(Toothache):", p_toothache)

# Q1 b) P(~Toothache)
p_not_toothache = marginal_probability('Toothache', '~Toothache')
print("P(~Toothache):", p_not_toothache)

# Q1 c) P(Catch | Cavity)
p_catch_given_cavity = conditional_probability('Catch', 'Catch', 'Cavity', 'Cavity')
print("P(Catch | Cavity):", p_catch_given_cavity)

# Q1 d) P(Cavity | Catch)
p_cavity_given_catch = conditional_probability('Cavity', 'Cavity', 'Catch', 'Catch')
print("P(Cavity | Catch):", p_cavity_given_catch)

# Q1 e) P(Catch | Cavity & Toothache)
# For this we need to consider both conditions Cavity=True and Toothache=True
joint_cavity_toothache_events = [(toothache, cavity, catch) for (toothache, cavity, catch), prob in joint_prob.items()
                                 if cavity == 'Cavity' and toothache == 'Toothache']
prob_joint_cavity_toothache = sum(joint_prob[event] for event in joint_cavity_toothache_events if event[2] == 'Catch')
prob_cavity_toothache = sum(joint_prob[event] for event in joint_cavity_toothache_events)
p_catch_given_cavity_toothache = prob_joint_cavity_toothache / prob_cavity_toothache if prob_cavity_toothache else 0
print("P(Catch | Cavity & Toothache):", p_catch_given_cavity_toothache)

# Q1 f) P(Cavity | Catch & Toothache)
# Same idea as above but for Cavity=True given Catch=True and Toothache=True
joint_catch_toothache_events = [(toothache, cavity, catch) for (toothache, cavity, catch), prob in joint_prob.items()
                                if catch == 'Catch' and toothache == 'Toothache']
prob_joint_cavity_catch_toothache = sum(joint_prob[event] for event in joint_catch_toothache_events if event[1] == 'Cavity')
prob_catch_toothache = sum(joint_prob[event] for event in joint_catch_toothache_events)
p_cavity_given_catch_toothache = prob_joint_cavity_catch_toothache / prob_catch_toothache if prob_catch_toothache else 0
print("P(Cavity | Catch & Toothache):", p_cavity_given_catch_toothache)


P(Toothache): 0.2
P(~Toothache): 0.7999999999999999
P(Catch | Cavity): 0.8999999999999999
P(Cavity | Catch): 0.5294117647058824
P(Catch | Cavity & Toothache): 0.9
P(Cavity | Catch & Toothache): 0.8709677419354839


# Problem 2


In [ ]:
import pandas as pd
from collections import defaultdict

# Data from Table 2
data = [
    {'League': 'SerieA', 'Position': 'CF', 'Preferred Foot': 'Left', 'Capped': 'Yes', 'Shortlisted': True},
    {'League': 'LaLiga', 'Position': 'LW', 'Preferred Foot': 'Right', 'Capped': 'No', 'Shortlisted': True},
    {'League': 'LaLiga', 'Position': 'CF', 'Preferred Foot': 'Right', 'Capped': 'Yes', 'Shortlisted': False},
    {'League': 'Premier League', 'Position': 'CF', 'Preferred Foot': 'Left', 'Capped': 'Yes', 'Shortlisted': True},
    {'League': 'Premier League', 'Position': 'LW', 'Preferred Foot': 'Left', 'Capped': 'Yes', 'Shortlisted': False},
    {'League': 'Serie A', 'Position': 'RW', 'Preferred Foot': 'Left', 'Capped': 'Yes', 'Shortlisted': False},
    {'League': 'Serie A', 'Position': 'CF', 'Preferred Foot': 'Right', 'Capped': 'No', 'Shortlisted': True},
    {'League': 'Premier League', 'Position': 'LW', 'Preferred Foot': 'Left', 'Capped': 'No', 'Shortlisted': False},
    {'League': 'Serie A', 'Position': 'RW', 'Preferred Foot': 'Right', 'Capped': 'No', 'Shortlisted': True},
    {'League': 'LaLiga', 'Position': 'RW', 'Preferred Foot': 'Left', 'Capped': 'No', 'Shortlisted': False},
    {'League': 'LaLiga', 'Position': 'RW', 'Preferred Foot': 'Right', 'Capped': 'No', 'Shortlisted': True},
    {'League': 'Premier League', 'Position': 'CF', 'Preferred Foot': 'Right', 'Capped': 'No', 'Shortlisted': False},
    {'League': 'LaLiga', 'Position': 'CF', 'Preferred Foot': 'Right', 'Capped': 'Yes', 'Shortlisted': True},
    {'League': 'Serie A', 'Position': 'LW', 'Preferred Foot': 'Left', 'Capped': 'No', 'Shortlisted': False}
]

df = pd.DataFrame(data)

# Calculate prior probabilities
prior_prob = df['Shortlisted'].value_counts(normalize=True).to_dict()

# Function to calculate conditional probabilities for an attribute given class label
def conditional_probs(df, feature, class_label):
    counts = df[df['Shortlisted'] == class_label][feature].value_counts()
    total = counts.sum()
    return (counts / total).to_dict()

# Calculate conditional probabilities
conditional_probabilities = {'True': defaultdict(dict), 'False': defaultdict(dict)}
for label in [True, False]:
    for feature in ['League', 'Position', 'Preferred Foot', 'Capped']:
        conditional_probabilities[str(label)][feature] = conditional_probs(df, feature, label)

# Function to calculate Naive Bayes probability for a given player
def naive_bayes_predict(player, prior_prob, conditional_probabilities):
    probabilities = {}
    for label in [True, False]:
        prob = prior_prob[label]
        for feature, value in player.items():
            prob *= conditional_probabilities[str(label)][feature].get(value, 1e-6)  # Small value to handle zero counts
        probabilities[label] = prob
    # Normalize probabilities
    total = sum(probabilities.values())
    for label in probabilities:
        probabilities[label] /= total
    return probabilities

# Players for prediction
player1 = {'League': 'LaLiga', 'Position': 'RW', 'Preferred Foot': 'Right', 'Capped': 'Yes'}
player2 = {'League': 'Premier League', 'Position': 'LW', 'Preferred Foot': 'Left', 'Capped': 'No'}

# Predicting for each player
prediction1 = naive_bayes_predict(player1, prior_prob, conditional_probabilities)
prediction2 = naive_bayes_predict(player2, prior_prob, conditional_probabilities)

print("Player 1 Prediction:", prediction1)
print("Player 2 Prediction:", prediction2)

# Decision based on the highest probability for each player
decision1 = "Shortlisted" if prediction1[True] > prediction1[False] else "Not Shortlisted"
decision2 = "Shortlisted" if prediction2[True] > prediction2[False] else "Not Shortlisted"

print(f"Player 1 would be: {decision1}")
print(f"Player 2 would be: {decision2}")


Player 1 Prediction: {True: 0.7894736842105263, False: 0.21052631578947367}
Player 2 Prediction: {True: 0.042553191489361694, False: 0.9574468085106382}
Player 1 would be: Shortlisted
Player 2 would be: Not Shortlisted


# Problem 3

In [ ]:
import pandas as pd
import numpy as np
import re
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load datasets (replace file paths with actual paths to your files)
newsgroup_train = pd.read_csv("newsgroup_train.csv")
newsgroup_test = pd.read_csv("newsgroup_test.csv")

# Extract features and labels
X_train = newsgroup_train['Text']  # Assuming 'Text' column holds the message content
y_train = newsgroup_train['Label']  # Assuming 'Label' column holds the category

X_test = newsgroup_test['Text']
y_test = newsgroup_test['Label']

class NaiveBayesTextClassifier:
    def __init__(self):
        self.word_counts = {}
        self.class_counts = {}
        self.vocab = set()
        self.total_counts = {}

    def preprocess(self, text):
        """Convert to lower case and remove non-word characters."""
        if isinstance(text, str):  # Check if the text is a string
            return re.findall(r'\b\w+\b', text.lower())
        else:
            return []  # Return empty list for non-string entries

    def fit(self, X, y):
        """Train the Naive Bayes classifier."""
        for text, label in zip(X, y):
            words = self.preprocess(text)
            self.vocab.update(words)  # Update vocabulary
            if label not in self.word_counts:
                self.word_counts[label] = {}
                self.class_counts[label] = 0
            self.class_counts[label] += 1

            for word in words:
                if word not in self.word_counts[label]:
                    self.word_counts[label][word] = 0
                self.word_counts[label][word] += 1

        # Total word counts for each class
        self.total_counts = {label: sum(counts.values()) for label, counts in self.word_counts.items()}

    def predict(self, X):
        """Predict class labels for the given text."""
        predictions = []
        vocab_size = len(self.vocab)

        for text in X:
            words = self.preprocess(text)
            class_scores = {}

            for label in self.class_counts.keys():
                prior = np.log(self.class_counts[label] / sum(self.class_counts.values()))
                likelihood = 0

                for word in words:
                    word_count = self.word_counts[label].get(word, 0)
                    # Apply Laplace smoothing
                    likelihood += np.log((word_count + 1) / (self.total_counts[label] + vocab_size))

                class_scores[label] = prior + likelihood

            # Choose the class with the highest score
            predictions.append(max(class_scores, key=class_scores.get))

        return predictions

# Initialize, train, and test the classifier
classifier = NaiveBayesTextClassifier()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, predictions))
print("Precision:", precision_score(y_test, predictions, average='macro'))
print("Recall:", recall_score(y_test, predictions, average='macro'))
print("F1 Score:", f1_score(y_test, predictions, average='macro'))
print("Confusion Matrix:\n", confusion_matrix(y_test, predictions))


Accuracy: 0.6666666666666666
Precision: 0.6887041800941706
Recall: 0.6235974414331227
F1 Score: 0.6229980585255342
Confusion Matrix:
 [[ 98  39   5]
 [ 18 153   7]
 [ 29  45  35]]
